language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer install

install:
  - travis_retry composer self-update && composer --version

script:
  - vendor\bin\phpunit tests

notifications:
   email: a.fiori@cheapnet.it
